/**
 * Core type definitions for multi-demo support system.
 * Defines interfaces for demo metadata, configuration, and registry entries.
 */

import { SlideComponentWithMetadata } from '../slides/SlideMetadata';
import { TimingConfig } from './timing/types';
import { SlideDurationBreakdown } from './timing/calculator';

/**
 * Metadata describing a demo presentation.
 */
export interface DemoMetadata {
  /** Unique stable identifier (kebab-case) */
  id: string;
  /** Display name for the demo */
  title: string;
  /** Short summary of the demo content */
  description?: string;
  /** Public path to thumbnail image */
  thumbnail?: string;
  /** Categorical labels for filtering/organizing demos */
  tags?: string[];
  
  /**
   * Optional duration information for this demo.
   * Provides detailed breakdown of audio and timing delays.
   * Generated by calculate-durations script.
   */
  durationInfo?: {
    /** Total audio duration in seconds (no delays) */
    audioOnly: number;
    /** Total segment delays in seconds (between segments within slides) */
    segmentDelays: number;
    /** Total slide delays in seconds (between slides) */
    slideDelays: number;
    /** Final delay in seconds (after last slide) */
    finalDelay: number;
    /** Total presentation duration in seconds (audio + all delays) */
    total: number;
    /** Optional detailed breakdown per slide */
    slideBreakdown?: SlideDurationBreakdown[];
  };
}

/**
 * Default playback mode for a demo presentation.
 */
export type DemoDefaultMode = 'narrated' | 'manual' | 'manual-audio';

/**
 * Complete configuration for a demo presentation.
 */
export interface DemoConfig {
  /** Unique identifier matching metadata */
  id: string;
  /** Demo metadata */
  metadata: DemoMetadata;
  /** Default playback mode (defaults to 'narrated' if not specified) */
  defaultMode?: DemoDefaultMode;
  /** Lazy loader for slide definitions */
  getSlides: () => Promise<SlideComponentWithMetadata[]>;
  
  /**
   * Optional timing configuration for this demo.
   * Sets default timing for all slides and segments.
   * Can be overridden at slide or segment level.
   *
   * @example
   * timing: { betweenSegments: 500, betweenSlides: 1000, afterFinalSlide: 2000 }
   */
  timing?: TimingConfig;
}

/**
 * Registry entry for a demo, supporting lazy loading.
 */
export interface DemoRegistryEntry {
  /** Unique identifier */
  id: string;
  /** Demo metadata (always available without loading full config) */
  metadata: DemoMetadata;
  /** Lazy loader for full demo configuration */
  loadConfig: () => Promise<DemoConfig>;
}