/**
 * Meeting Highlights COGS Reduction Demo Metadata
 *
 * This demo presents the Meeting Highlights product and its cost optimization journey,
 * showcasing a 70%+ reduction in computational costs while maintaining quality.
 */

import type { DemoMetadata, SlideDurationBreakdown } from '@framework';

/**
 * Detailed slide breakdown generated by calculate-durations script.
 * Provides per-slide timing information for duration analysis.
 */
const slideBreakdown: SlideDurationBreakdown[] = [
  { slideIndex: 1, slideTitle: "What is Meeting Highlights", chapterIndex: 1, totalDuration: 13.845334000000001, audioDuration: 11.845334000000001, delaysDuration: 2, segments: [{ segmentIndex: 0, audioDuration: 4.4, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 4.778667, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 2.666667, delayAfter: 1 }] },
  { slideIndex: 2, slideTitle: "How to Access via BizChat", chapterIndex: 1, totalDuration: 23.195999999999998, audioDuration: 19.695999999999998, delaysDuration: 3.5, segments: [{ segmentIndex: 0, audioDuration: 1.962667, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 3.2, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 5.866667, delayAfter: 0.5 }, { segmentIndex: 3, audioDuration: 2.133333, delayAfter: 0.5 }, { segmentIndex: 4, audioDuration: 2, delayAfter: 0.5 }, { segmentIndex: 5, audioDuration: 4.533333, delayAfter: 1 }] },
  { slideIndex: 3, slideTitle: "How to Access via SharePoint", chapterIndex: 1, totalDuration: 22.557333, audioDuration: 19.557333, delaysDuration: 3, segments: [{ segmentIndex: 0, audioDuration: 3.157333, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 2.666667, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 5.733333, delayAfter: 0.5 }, { segmentIndex: 3, audioDuration: 1.466667, delayAfter: 0.5 }, { segmentIndex: 4, audioDuration: 6.533333, delayAfter: 1 }] },
  { slideIndex: 1, slideTitle: "Team Collaboration & Architecture", chapterIndex: 2, totalDuration: 58.130666000000005, audioDuration: 53.130666000000005, delaysDuration: 5, segments: [{ segmentIndex: 0, audioDuration: 10.533333, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 6.133333, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 4.933333, delayAfter: 0.5 }, { segmentIndex: 3, audioDuration: 4.533333, delayAfter: 0.5 }, { segmentIndex: 4, audioDuration: 6.133333, delayAfter: 0.5 }, { segmentIndex: 5, audioDuration: 3.2, delayAfter: 0.5 }, { segmentIndex: 6, audioDuration: 2.986667, delayAfter: 0.5 }, { segmentIndex: 7, audioDuration: 4.266667, delayAfter: 0.5 }, { segmentIndex: 8, audioDuration: 10.410667, delayAfter: 1 }] },
  { slideIndex: 1, slideTitle: "Highlight Types", chapterIndex: 4, totalDuration: 41.773334, audioDuration: 38.773334, delaysDuration: 3, segments: [{ segmentIndex: 0, audioDuration: 5.6, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 12.533333, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 8.266667, delayAfter: 0.5 }, { segmentIndex: 3, audioDuration: 4.778667, delayAfter: 0.5 }, { segmentIndex: 4, audioDuration: 7.594667, delayAfter: 1 }] },
  { slideIndex: 1, slideTitle: "Challenge Framing", chapterIndex: 5, totalDuration: 13.533333, audioDuration: 12.533333, delaysDuration: 1, segments: [{ segmentIndex: 0, audioDuration: 12.533333, delayAfter: 1 }] },
  { slideIndex: 1, slideTitle: "Unified Convergence", chapterIndex: 6, totalDuration: 13, audioDuration: 12, delaysDuration: 1, segments: [{ segmentIndex: 0, audioDuration: 12, delayAfter: 1 }] },
  { slideIndex: 4, slideTitle: "Token Optimization", chapterIndex: 6, totalDuration: 8.733333, audioDuration: 7.733333, delaysDuration: 1, segments: [{ segmentIndex: 0, audioDuration: 7.733333, delayAfter: 1 }] },
  { slideIndex: 2, slideTitle: "GPU Optimization", chapterIndex: 7, totalDuration: 6.2, audioDuration: 5.2, delaysDuration: 1, segments: [{ segmentIndex: 0, audioDuration: 5.2, delayAfter: 1 }] },
  { slideIndex: 4, slideTitle: "Quality Improvement", chapterIndex: 7, totalDuration: 9, audioDuration: 8, delaysDuration: 1, segments: [{ segmentIndex: 0, audioDuration: 8, delayAfter: 1 }] },
  { slideIndex: 5, slideTitle: "Path to GA", chapterIndex: 7, totalDuration: 5.933333, audioDuration: 4.933333, delaysDuration: 1, segments: [{ segmentIndex: 0, audioDuration: 4.933333, delayAfter: 1 }] },
  { slideIndex: 1, slideTitle: "User Satisfaction", chapterIndex: 8, totalDuration: 15.764001, audioDuration: 13.264001, delaysDuration: 2.5, segments: [{ segmentIndex: 0, audioDuration: 3.066667, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 3.066667, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 2.266667, delayAfter: 0.5 }, { segmentIndex: 3, audioDuration: 4.864, delayAfter: 1 }] },
  { slideIndex: 1, slideTitle: "Testimonials", chapterIndex: 9, totalDuration: 29.367998999999998, audioDuration: 26.367998999999998, delaysDuration: 3, segments: [{ segmentIndex: 0, audioDuration: 2.133333, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 6.8, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 7.168, delayAfter: 0.5 }, { segmentIndex: 3, audioDuration: 5.733333, delayAfter: 0.5 }, { segmentIndex: 4, audioDuration: 4.533333, delayAfter: 1 }] },
  { slideIndex: 2, slideTitle: "Thank You", chapterIndex: 9, totalDuration: 17.610583, audioDuration: 14.110582999999998, delaysDuration: 3.5, segments: [{ segmentIndex: 0, audioDuration: 2.666667, delayAfter: 0.5 }, { segmentIndex: 1, audioDuration: 3.310583, delayAfter: 0.5 }, { segmentIndex: 2, audioDuration: 4.8, delayAfter: 0.5 }, { segmentIndex: 3, audioDuration: 3.333333, delayAfter: 2 }] }
];

export const metadata: DemoMetadata = {
  id: 'meeting-highlights',
  title: 'Meeting Highlights COGS Reduction',
  description: 'Presentation showcasing the Meeting Highlights product and the technical optimizations that reduced computational costs by over 70% while maintaining quality. Features product overview, team collaboration, COGS challenge, optimization solution, business impact, user satisfaction, and testimonials.',
  thumbnail: '/images/meeting-highlights/meeting_highlights_thumbnail.jpeg',
  tags: ['meeting-highlights', 'llm', 'optimization', 'cogs', 'ai', 'product'],

  /**
   * External narration configuration.
   * Loads narration text from /public/narration/meeting-highlights/narration.json
   * Strict mode: Errors if JSON is missing (inline narrationText removed in Phase 7).
   */
  useExternalNarration: true,
  narrationFallback: 'error', // Strict mode - inline narrationText removed

  /**
   * Duration information calculated by calculate-durations script.
   *
   * Breakdown:
   * - Audio Only: 4:07 (247s) - Total narration audio across all slides
   * - Start Silence: 1s - Blank screen before first slide (beforeFirstSlide)
   * - Segment Delays: 16.5s - Pauses between segments within slides (500ms each)
   * - Slide Delays: 13s - Transitions between slides (1000ms each)
   * - Final Delay: 2s - Hold time after final slide
   * - Total Duration: 4:39 (280s) - Complete presentation runtime
   *
   * Note: All timing values use defaults from demo timing config:
   * betweenSegments=500ms, betweenSlides=1000ms, afterFinalSlide=2000ms, beforeFirstSlide=1000ms
   */
  durationInfo: {
    audioOnly: 247,       // Audio duration in seconds (rounded from 247.145s)
    segmentDelays: 17,    // Between-segment delays total (rounded from 16.5s)
    slideDelays: 13,      // Between-slide delays total
    finalDelay: 2,        // After final slide delay
    startSilence: 1,      // Before first slide silence
    total: 280,           // Complete presentation duration (rounded from 279.645s)
    slideBreakdown
  }
};
